apiVersion: apps/v1
kind: Deployment
metadata:
  name: devday-app
  namespace: examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devday-app
  template:
    metadata:
      labels:
        app: devday-app
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: devday-app
          image: nrt.ocir.io/orasejapan/shukawam/devday-app:1.0.2
          ports:
            - name: api
              containerPort: 8501
          command: ["ddtrace-run", "streamlit", "run", "main.py"]
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devday-secret
                  key: GOOGLE_API_KEY
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: devday-secret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devday-secret
                  key: PASSWORD
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: devday-secret
                  key: DSN
            - name: COMPARTMENT_ID
              valueFrom:
                secretKeyRef:
                  name: devday-secret
                  key: COMPARTMENT_ID
            # Datadog
            - name: DD_LLMOBS_ENABLED
              value: "1" # Enabled
            - name: DD_LLMOBS_ML_APP
              value: devday
            - name: DD_LLMOBS_AGENTLESS_ENABLED
              value: "false" # DefaultでFalseだが、有効にならないので明示的に指定する
            # Traceloop via OpenLLMetry
            - name: TRACELOOP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devday-secret
                  key: TRACELOOP_API_KEY
      imagePullSecrets:
        - name: ocir-secret
